server:
  port: 8081

spring:
  data:
    mongodb:
      port: 27026
      database: product
  application:
    name: product-service
  webflux:
    base-path: /product

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/devteria